### ISSUE TITLE
Can't get tags to work (404)

### ISSUE THREAD

**Issue by TonySpegel** [zbrox/anpu-zola-theme#4]
Hi there, I'd like to use your theme and tried to integrate it in mine by following your READ.ME 
and did everything what is mentioned there. So I started a new project by running `zola init`said yes to everything and then cloned this repo into my themes directory and also edited my config.toml - which now looks like this:
```toml
base_url = "https://example.com"

compile_sass = true
build_search_index = true

theme = "anpu"

taxonomies = [
    { name = "categories", rss = true},
    { name = "tags", rss = true},
]

[markdown]
highlight_code = true

[extra]
anpu_menu_links = [
    { url = "$BASE_URL/about/", name = "About" },
    { url = "$BASE_URL/tags/", name = "Tags" },
]
anpu_date_format = "%e %B %Y"
```
So pretty much the same and without overwriting it this should be it right? But if I follow the tags link in the main menu all I get is 
```bash
404: Page not found
Sorry, this page doesn't seem to exist.
```
am I missing something which needs to be done in order to have this site by itself start working? I haven't put any blog posts in it yet or did anything beside the things I've mentioned - although I have tried overwriting the file by putting them in the same structure in my site.

I appreciate any help and than you :)
